volumes:
  caddy_data:
  caddy_config:

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui
    container_name: 3x-ui
    restart: always
    volumes:
      - ./3x-ui-data/:/etc/x-ui/
    expose:
      - "2053"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
